# Generated by Django 3.2.4 on 2021-12-19 23:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210624_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='trailer_link',
        ),
        migrations.AddField(
            model_name='movie',
            name='films',
            field=models.FileField(default=datetime.datetime(2021, 12, 19, 23, 59, 33, 720015, tzinfo=utc), upload_to='films', verbose_name='Filim yuklang'),
            preserve_default=False,
        ),
    ]
